# Generated by Django 5.1.6 on 2025-06-26 10:39

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_id'),  
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=255, default=''),
        ),
    ]



