# Generated by Django 3.1.12 on 2025-01-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourCustomUserModel',
        ),
    ]
